### ISSUE TITLE
Quality Requirements - Nonfunctional goals, goal-question-metric breakdown graph, Testable NFR specification

### ISSUE THREAD

**Issue by jacob-barna** [deepbaconattackers/deepbaconattackers#28]
Specify testable quality requirements applicable to the application's domain: performance, reliability, safety, security, privacy, etc.

**Comment by jpstratman** [comment]
Quality Requirements - specification of product-related nonfunctional requirement(s) relevant to the project

- Nonfunctional goals - related to goal model elements
- Goal-question-metric breakdown graph
- Testable NFR specification based on the metrics
