### ISSUE TITLE
Fix sequence model

### ISSUE THREAD

**Issue by jpstratman** [deepbaconattackers/deepbaconattackers#66]
Sequence model: which is being edited: maintenance issue or ticket? Drill down the “System” to show the interaction of the various objects. Follow the heuristics for creating a sequence diagram. You may also include the screen object such as “Edit Issue (Ticket?) Page”.

**Comment by spacetag** [comment]
I updated the Sequence Model!

Note though: We did made a distinction between "Issue" and "Ticket", but sometimes we use "Issue" when we really mean "Ticket". We should fix this (see #77)
